# https://kubernetes.io/docs/concepts/configuration/secret/
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth
  namespace: kube-system
type: Opaque
data:
  PROVIDERS_OIDC_CLIENT_SECRET: NWNXXXXXXXXXXXXXXXXXXXXXXXXXXJjMjcw
  SECRET: YjNjXXXXXXXXXXXXXXXXXXXXXXXX2ZhMGU=
